# Copyright 2024 Google LLC.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#      https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a separate workspace to avoid pulling additional dependencies to the
# main repo.
workspace(name = "kv-test-client")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

git_repository(
    name = "kv-server",
    commit = "119f4ceb56728c0e5a00ab10f84af53ce010682e",
    remote = "sso://team/kiwi-air-force-eng-team/kv-server",
)

http_archive(
    name = "google_cloud_cpp",
    sha256 = "6f58213e2af16326392da84cd8a52af78cb80bc47338eb87e87d14c14c0e6bad",
    strip_prefix = "google-cloud-cpp-2.25.0",
    url = "https://github.com/googleapis/google-cloud-cpp/archive/v2.25.0.tar.gz",
)

load("@google_cloud_cpp//bazel:google_cloud_cpp_deps.bzl", "google_cloud_cpp_deps")

google_cloud_cpp_deps()

load("@com_google_googleapis//:repository_rules.bzl", "switched_rules_by_language")

switched_rules_by_language(
    name = "com_google_googleapis_imports",
    cc = True,
    grpc = True,
)

git_repository(
    name = "google_privacysandbox_servers_common",
    commit = "8e3a351b33ed127e52584b7769ece6205492b725",
    remote = "sso://team/privacy-sandbox-team/servers/common",
)

http_archive(
    name = "com_github_google_quiche",
    sha256 = "563cbc483a006d4999e2e9b1114fec02cdc904fcdafa29721e4e6d816c8d648a",
    strip_prefix = "quiche-cc0614c8ab209e297f7b17ab3d04618fee327a4f",
    urls = ["https://github.com/google/quiche/archive/cc0614c8ab209e297f7b17ab3d04618fee327a4f.tar.gz"],
)

http_archive(
    name = "com_google_googleurl",
    sha256 = "a1bc96169d34dcc1406ffb750deef3bc8718bd1f9069a2878838e1bd905de989",
    urls = ["https://storage.googleapis.com/quiche-envoy-integration/googleurl_9cdb1f4d1a365ebdbcbf179dadf7f8aa5ee802e7.tar.gz"],
)

http_archive(
    name = "com_google_quic_trace",
    sha256 = "079331de8c3cbf145a3b57adb3ad4e73d733ecfa84d3486e1c5a9eaeef286549",
    strip_prefix = "quic-trace-c7b993eb750e60c307e82f75763600d9c06a6de1",
    urls = ["https://github.com/google/quic-trace/archive/c7b993eb750e60c307e82f75763600d9c06a6de1.tar.gz"],
)
