package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "credentials",
    srcs = ["credentials.cc"],
    hdrs = ["credentials.h"],
    deps = [
        "@com_github_grpc_grpc//:grpc++",
    ],
)
